cc_library(
    name = "include",
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    strip_include_prefix = "/include",
)

cc_library(
    name = "with_extra_prefix",
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
)
