cc_library(
    name = "tools",
    deps = [
        ":headers",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "headers",
    hdrs = ["sst_dump_tool_imp.h"],
    deps = [
        "//include",
        "//options:headers",
        "//util:headers",
    ],
    visibility = ["//visibility:public"],
)
